services:
  a0:
    build: .
    shm_size: "2g"     # Playwright stability
    environment:
      - VNC_PW=${VNC_PW:-changeme}
      # Optionally add model keys here or via A0 UI:
      # - OPENAI_API_KEY=...
      # - ANTHROPIC_API_KEY=...
    volumes:
      - a0-logs:/opt/agent-zero/logs
      - a0-home:/home/kasm-user
    restart: unless-stopped

volumes:
  a0-logs:
  a0-home:
