version: "3.9"

services:
  kali-az:
    build: .
    shm_size: "2gb"
    environment:
      # KasmVNC login (strong password!)
      - VNC_PW=${KASM_VNC_PW}
      # Agent Zero model keys (set in Coolify)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    labels:
      - traefik.enable=true

      # Route 1: streamed Kali desktop (KasmVNC on 6901)
      - traefik.http.routers.kali.rule=Host(`kali.uptopoint.net`)
      - traefik.http.routers.kali.entryPoints=websecure
      - traefik.http.routers.kali.tls=true
      - traefik.http.routers.kali.service=kali-svc
      - traefik.http.services.kali-svc.loadbalancer.server.port=6901

      # Route 2: Agent Zero UI (port 80 in same container)
      - traefik.http.routers.az.rule=Host(`az-kali.uptopoint.net`)
      - traefik.http.routers.az.entryPoints=websecure
      - traefik.http.routers.az.tls=true
      - traefik.http.routers.az.service=az-svc
      - traefik.http.services.az-svc.loadbalancer.server.port=80
