version: "3.9"
services:
  az-kasm-kali:
    build: .
    container_name: az-kasm-kali
    ports:
      - "6901:6901"     # Kasm desktop (web VNC)
      - "50001:50001"   # AgentZero UI
    environment:
      - VNC_PW=${VNC_PW:-changeme}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    shm_size: "1g"      # Chromium stability
    restart: unless-stopped
    volumes:
      - az_home:/home/kasm-user
volumes:
