services:
  a0:
    build: .
    shm_size: "2g"        # Playwright/Chromium stability
    environment:
      # Change this in Coolify Secrets/Envs before deploying
      - VNC_PW=${VNC_PW:-changeme}

      # Add your LLM provider keys here or set them later in A0 UI:
      # - OPENAI_API_KEY=...
      # - ANTHROPIC_API_KEY=...
      # - OPENROUTER_API_KEY=...
    volumes:
      # Persist A0 logs/memory and Kali user config if you like
      - a0-logs:/opt/agent-zero/logs
      - a0-home:/home/kasm-user
    restart: unless-stopped

volumes:
  a0-logs:
  a0-home:
